services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: portal_locadora_db
    restart: unless-stopped
    ports:
      - '54321:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portal_locadora
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portal_network

  # PgAdmin - Interface Web para PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: portal_locadora_pgadmin
    restart: unless-stopped
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@portaldalocadora.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - portal_network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  portal_network:
    driver: bridge
